[build]
  publish = "public"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  USE_SUPABASE = "true"

[functions]
  external_node_modules = ["express", "ejs"]
  node_bundler = "esbuild"
  included_files = ["src/views/**/*", "src/views/**/*.ejs"]

[dev]
  command = "npm run dev"
  port = 3000
  publish = "public"
  functions = "netlify/functions"

# API routes redirects to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/dashboard/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/profile/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/jobs/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/applications/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/messages/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/advice/*"
  to = "/.netlify/functions/server"
  status = 200

# Catch-all for SPA routing
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/dist/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]